title: "pirix.org"
url: "http://pirix.org"
author: "Thomas Gatzweiler"

destination: _site
plugins: _plugins
exclude: [Rakefile]
permalink: pretty

pygments: true
lsi: false
future: false
markdown: maruku